<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"></meta>
  <meta http-equiv="X-UA-Compatible" content="ie-edge"></meta>
  <title>promise</title>
</head>
<body>
  <script>
    // resolve 、reject 、all 、race

    let promise = new Promise((resolve,reject)=>{
      resolve(1221)
      //reject(123)
    })

    promise.then(res=>{
      //resolve
      console.log('成功')
      console.log(res)
    }).catch(err =>{
      //reject
      console.log('失败')
      console.log(err)
    })

    //链式
    function promise1(status) {
      return new Promise((resolve,reject)=>{
        if (status) {
          resolve('第一个promise1返回数据成功');
          console.log('第一个promise1成功')
        }else{
          reject('第一个promise1返回数据失败')
          console.log("第一个promise1失败") 
        }
      })
    }

    function promise2(status) {
      return new Promise((resolve,reject)=>{
        if (status) {
          resolve('第二个promise2返回数据成功');
          console.log('第二个promise2成功')
        }else{
          reject('第二个promise2返回数据失败')
          console.log("第二个promise2失败") 
        }
      })
    }

    promise1(true).then(res=>{ //第一个
        console.log(res);
        return promise2(true);
    }).then(res=>{    //第二个
      console.log(res);
    }).catch(error=>{
        console.log(error)
    })

    //all方法 数组内有promise 必须全部成功才会执行true （then）回调,只要有一个失败就走catch
    Promise.all([promise1(true),promise2(true)]).then(res=>{
      console.log("全部成功")
    }).catch(err=>{
      console.log("可能部分失败了")
    })

    //race方法 数组当在执行的时候 遇到的返回的结果是resolve 一直执行链式
    Promise.race([promise1(false),promise2(true)]).then(res=>{
      console.log("全部成功")
    }).catch(err=>{
      console.log("可能部分失败了")
    })
  </script>
</body>
</html>